# Generated by Django 6.0 on 2026-10-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_tag_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, help_text='Optional CSS color name for UI accents.', max_length=50),
        ),
    ]
